"""Convert nucleotide SNP edits into amino-acid substitutions."""

from __future__ import annotations

CODON_TO_AA = {
    "TCA": "S",
    "TCC": "S",
    "TCG": "S",
    "TCT": "S",
    "TTC": "F",
    "TTT": "F",
    "TTA": "L",
    "TTG": "L",
    "TAC": "Y",
    "TAT": "Y",
    "TAA": "!",
    "TAG": "!",
    "TGC": "C",
    "TGT": "C",
    "TGA": "!",
    "TGG": "W",
    "CTA": "L",
    "CTC": "L",
    "CTG": "L",
    "CTT": "L",
    "CCA": "P",
    "CCC": "P",
    "CCG": "P",
    "CCT": "P",
    "CAC": "H",
    "CAT": "H",
    "CAA": "Q",
    "CAG": "Q",
    "CGA": "R",
    "CGC": "R",
    "CGG": "R",
    "CGT": "R",
    "ATA": "I",
    "ATC": "I",
    "ATT": "I",
    "ATG": "M",
    "ACA": "T",
    "ACC": "T",
    "ACG": "T",
    "ACT": "T",
    "AAC": "N",
    "AAT": "N",
    "AAA": "K",
    "AAG": "K",
    "AGC": "S",
    "AGT": "S",
    "AGA": "R",
    "AGG": "R",
    "GTA": "V",
    "GTC": "V",
    "GTG": "V",
    "GTT": "V",
    "GCA": "A",
    "GCC": "A",
    "GCG": "A",
    "GCT": "A",
    "GAC": "D",
    "GAT": "D",
    "GAA": "E",
    "GAG": "E",
    "GGA": "G",
    "GGC": "G",
    "GGG": "G",
    "GGT": "G",
}


def _to_codons(sequence: list[str]) -> list[tuple[str, str, str]]:
    return list(zip(*[iter(sequence)] * 3, strict=False))


def convert_snps_to_aa(
    sequence: str,
    strand: str,
    start_pos: int,
    end_pos: int,
    positions: list[int],
    refs: list[str],
    alts: list[str],
) -> list[str]:
    """Return amino-acid mutation notations generated by SNP edits."""
    if len(positions) != len(refs) or len(positions) != len(alts):
        raise ValueError("positions, refs, and alts must have equal length")

    seq = list(sequence.upper())
    refs_codons = _to_codons(seq)
    output: list[str] = []

    for pos, ref, alt in zip(positions, refs, alts, strict=False):
        if strand == "+":
            idx = pos - start_pos
        elif strand == "-":
            idx = end_pos - pos
        else:
            raise ValueError("strand must be '+' or '-'")

        if idx < 0 or idx >= len(seq):
            continue
        if seq[idx] != ref.upper():
            continue

        edited = seq.copy()
        edited[idx] = alt.upper()
        alt_codons = _to_codons(edited)

        for codon_idx, (before, after) in enumerate(
            zip(refs_codons, alt_codons, strict=False),
            start=1,
        ):
            before_str = "".join(before)
            after_str = "".join(after)
            if before_str == after_str:
                continue
            output.append(f"{CODON_TO_AA[before_str]}{codon_idx}{CODON_TO_AA[after_str]}")

    return output
